project_id = "jqqsszwbbxvevebmebfm"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.ai-dialogue]
    verify_jwt = false
  [functions.telegram-reminders]
    verify_jwt = false
  [functions.telegram-webhook]
    verify_jwt = false
  [functions.telegram-broadcast]
    verify_jwt = false
  [functions.notify-duel]
    verify_jwt = false
  [functions.generate-exercises]
    verify_jwt = false
  [functions.notify-duel-result]
    verify_jwt = false
  [functions.check-writing]
    verify_jwt = false
