// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-progress.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function clientFor(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_progress_default = defineTool({
  name: "get_progress",
  title: "Get my learning progress",
  description: "Returns the signed-in KLAR user's total XP, coin balance, current level, and profile display name.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor(ctx);
    const userId = ctx.getUserId();
    const [profile, xp, coins] = await Promise.all([
      supabase.from("profiles").select("display_name, nickname, level").eq("user_id", userId).maybeSingle(),
      supabase.from("user_xp").select("total_xp").eq("user_id", userId).maybeSingle(),
      supabase.from("user_coins").select("balance").eq("user_id", userId).maybeSingle()
    ]);
    const result = {
      display_name: profile.data?.display_name ?? null,
      nickname: profile.data?.nickname ?? null,
      level: profile.data?.level ?? null,
      total_xp: xp.data?.total_xp ?? 0,
      coins: coins.data?.balance ?? 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-my-words.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function clientFor2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_words_default = defineTool2({
  name: "list_my_words",
  title: "List my saved vocabulary",
  description: "Returns the signed-in user's saved German vocabulary from their KLAR dictionary, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max number of words to return."),
    search: z.string().trim().max(80).optional().describe("Optional substring filter on the German word.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor2(ctx);
    let q = supabase.from("saved_words").select("word, translation, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (search) q = q.ilike("word", `%${search}%`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { words: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
function clientFor3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_courses_default = defineTool3({
  name: "list_courses",
  title: "List available KLAR courses",
  description: "Lists KLAR Academy courses visible to the signed-in user (id, title, level, description, price).",
  inputSchema: {
    level: z2.enum(["A1", "A2", "B1", "B2", "C1"]).optional().describe("Optional CEFR level filter."),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ level, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = clientFor3(ctx);
    let q = supabase.from("courses").select("id, title, description, level, price, available").eq("available", true).order("created_at", { ascending: false }).limit(limit);
    if (level) q = q.eq("level", level);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jqqsszwbbxvevebmebfm";
var mcp_default = defineMcp({
  name: "klar-academy-mcp",
  title: "KLAR Academy",
  version: "0.1.0",
  instructions: "Tools for the KLAR language academy. Use get_progress to read the signed-in user's XP/coins, list_my_words to browse their saved German vocabulary, and list_courses to see available Academy courses.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_progress_default, list_my_words_default, list_courses_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
